name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # 👈 This is mandatory

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Copy Code to VPS
        run: |
          rsync -avz --progress --delete -e "ssh -i ~/.ssh/id_ed25519" . \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/deploy/tata/test-github-action
